<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('certificates', function (Blueprint $table) {
            // pending = the student completed it, the trainer hasn't uploaded yet
            // issued  = ready, the student can download it
            $table->enum('status', ['pending', 'issued'])->default('issued')->after('certificate_no');

            // manual = the trainer uploaded a PDF | auto = generated by dompdf
            $table->enum('source', ['auto', 'manual'])->default('auto')->after('status');

            // base64 PDF — stored in the DB, NOT on disk (Render's disk is ephemeral)
            $table->longText('file_blob')->nullable()->after('file_path');
            $table->string('file_mime')->nullable()->after('file_blob');

            $table->foreignId('uploaded_by')->nullable()->after('file_mime')
                  ->constrained('users')->nullOnDelete();

            // for auto mode — will stay empty for now
            $table->json('template_snapshot')->nullable()->after('uploaded_by');

            $table->index('status');
        });
    }

    public function down(): void
    {
        Schema::table('certificates', function (Blueprint $table) {
            $table->dropForeign(['uploaded_by']);
            $table->dropIndex(['status']);
            $table->dropColumn([
                'status', 'source', 'file_blob',
                'file_mime', 'uploaded_by', 'template_snapshot',
            ]);
        });
    }
};